# Generated by Django 4.2.3 on 2023-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMMITTEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_no', models.IntegerField()),
                ('meal_rate', models.FloatField()),
            ],
        ),
    ]
