# Generated by Django 4.2.3 on 2023-07-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activation_request',
            options={'verbose_name': 'Activation Request', 'verbose_name_plural': 'Activation Requests'},
        ),
        migrations.AlterModelOptions(
            name='deactivation_request',
            options={'verbose_name': 'Deactivation Request', 'verbose_name_plural': 'Deactivation Requests'},
        ),
    ]
