# Generated by Django 4.2.3 on 2023-07-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_activation_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation_request',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deactivation_request',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
